"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3


[[blocks]]
type = "prompt"
alignment = "left"
newline = true  # This should be at the block level
  [[blocks.segments]]
  type = "text"
  style = "plain"
  background = "transparent"
  template = ""
  [[blocks.segments]]
  type = "path"
  style = "plain"
  background = "transparent"
  foreground = "p:lavender"
  template = "{{ .Path }}"

    [blocks.segments.properties]
      style = "full"

[[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <p:teal>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'

    [blocks.segments.properties]
      branch_icon = ''
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'p:yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 1000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}p:red{{end}}",
      "{{if eq .Code 0}}p:peach{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:peach{{end}}",
  ]
  background = 'transparent'
  template = '❯'

[secondary_prompt]
  foreground = 'p:peach'
  background = 'transparent'
  template = '❯❯'

[palette]
lavender = "#b4befe"
peach = "#fab387"
teal = "#94e2d5"
red = "#f38ba8"
yellow = ""
